set_property SRC_FILE_INFO {cfile:C:/Users/ariya/OneDrive/Desktop/project_1/project_1/project_1.srcs/constrs_1/imports/project_1/pin_assignment.xdc rfile:../../../project_1.srcs/constrs_1/imports/project_1/pin_assignment.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18                [get_ports clk_0]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15                [get_ports rst_0]
