package main.visitor;

import main.ast.nodes.*;
import main.ast.nodes.ConstVal.*;
import main.ast.nodes.Operators.AssignOp;
import main.ast.nodes.Operators.Unary;
import main.ast.nodes.Stmt.*;
import main.ast.nodes.Stmt.JumpStmt.*;
import main.ast.nodes.Stmt.IterationStmt.*;
import main.ast.nodes.Expression.*;
import main.ast.nodes.Expression.BinaryExpression.*;
import main.ast.nodes.Types.*;
import main.ast.nodes.Expression.PostExpression.*;
import main.ast.nodes.Expression.PreExpression.*;
import main.ast.nodes.Stmt.SelectionStmt.*;
import main.ast.nodes.Types.Double_;
import main.ast.nodes.Types.Float_;
import main.ast.nodes.Types.Long_;
import main.ast.nodes.Types.Short_;
import main.ast.nodes.Types.Void_;

public interface IVisitor<T> {

    T visit(AbstractDeclaratorDirect node);
    T visit(AbstDeclaratorPointer node);
    T visit(ArgExprLst node);
    T visit(ArrAccess node);
    T visit(AssignExpr node);
    T visit(BinaryExpr node);
    T visit(Bool_ node);
    T visit(Break node);
    T visit(CastExpressionAgain node);
    T visit(CastExprAlone node);
    T visit(CastExprExpr node);
    T visit(CharConst node);
    T visit(Char_ node);
    T visit(CommaExpr node);
    T visit(CommonExpr node);
    T visit(CompoundLiteral node);
    T visit(Compound node);
    T visit(CondExpr node);
    T visit(Const node);
    T visit(ConstVal node);
    T visit(Continue node);
    T visit(Declaration node);
    T visit(DecLst node);
    T visit(DeclarationSpecs node);
    T visit(Declarator node);
    T visit(Designation node);
    T visit(DigitSeq node);
    T visit(DirectAbstDec1 node);
    T visit(DirectAbstDec2 node);
    T visit(DirectAbstDec3 node);
    T visit(DirectAbstDec4 node);
    T visit(DirectAbstDec5 node);
    T visit(DirectDec1 node);
    T visit(DirectDec2 node);
    T visit(DoWhile node);
    T visit(Double_ node);
    T visit(Elif node);
    T visit(Else node);
    T visit(Expr node);
    T visit(FloatConst node);
    T visit(Float_ node);
    T visit(For node);
    T visit(ForCond1 node);
    T visit(ForCond2 node);
    T visit(ForDec node);
    T visit(ForExpr node);
    T visit(FunctionCall node);
    T visit(FuncDef node);
    T visit(IF node);
    T visit(Identifier node);
    T visit(IdentifierLst node);
    T visit(InitDec node);
    T visit(InitDecLst node);
    T visit(InitLst node);
    T visit(IntConst node);
    T visit(Int_ node);
    T visit(Long_ node);
    T visit(ParameterDeclarationType1 node);
    T visit(ParamDec2 node);
    T visit(ParamLst node);
    T visit(Pointer node);
    T visit(PostDec node);
    T visit(PostInc node);
    T visit(PreDec node);
    T visit(PreInc node);
    T visit(PreSizeOf node);
    T visit(Program node);
    T visit(Return node);
    T visit(Short_ node);
    T visit(Signed_ node);
    T visit(SizeofType node);
    T visit(SpecQualifierLst1 node);
    T visit(SpecQualifierLst2 node);
    T visit(Star node);
    T visit(StrLiteralExp node);
    T visit(TransUnit node);
    T visit(TypeDef node);
    T visit(TypeName node);
    T visit(Unsigned_ node);
    T visit(UnaryExpr node);
    T visit(Void_ node);
    T visit(While node);
    T visit(AbstractDeclarator node);
    T visit(Expression node);
    T visit(ParanExpr node);
    T visit(IdentifierExpr node);
    T visit(Unary node);
    T visit(AssignOp node);
}