# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/project_1/pin_assignment.xdc

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Adder_0/design_2_Adder_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_Adder_0 || ORIG_REF_NAME==design_2_Adder_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_FourConstant_0/design_2_FourConstant_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_FourConstant_0 || ORIG_REF_NAME==design_2_FourConstant_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_IFreg_0/design_2_IFreg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_IFreg_0 || ORIG_REF_NAME==design_2_IFreg_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Mux_0/design_2_Mux_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_Mux_0 || ORIG_REF_NAME==design_2_Mux_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_PC_0/design_2_PC_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_PC_0 || ORIG_REF_NAME==design_2_PC_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_debouncer_0_0/design_2_debouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_debouncer_0_0 || ORIG_REF_NAME==design_2_debouncer_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ila_0_0/design_2_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ila_0_0 || ORIG_REF_NAME==design_2_ila_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlslice_0_0/design_2_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlslice_0_0 || ORIG_REF_NAME==design_2_xlslice_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_CUMUX_0_0/design_2_CUMUX_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_CUMUX_0_0 || ORIG_REF_NAME==design_2_CUMUX_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ConditionCheck_0_0/design_2_ConditionCheck_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ConditionCheck_0_0 || ORIG_REF_NAME==design_2_ConditionCheck_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ControlUnit_0_0/design_2_ControlUnit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ControlUnit_0_0 || ORIG_REF_NAME==design_2_ControlUnit_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_RegMux_0_0/design_2_RegMux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_RegMux_0_0 || ORIG_REF_NAME==design_2_RegMux_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_RegisterFile_0_0/design_2_RegisterFile_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_RegisterFile_0_0 || ORIG_REF_NAME==design_2_RegisterFile_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlslice_1_0/design_2_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlslice_1_0 || ORIG_REF_NAME==design_2_xlslice_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlslice_2_0/design_2_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlslice_2_0 || ORIG_REF_NAME==design_2_xlslice_2_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlslice_3_0/design_2_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlslice_3_0 || ORIG_REF_NAME==design_2_xlslice_3_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlslice_2_2/design_2_xlslice_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlslice_2_2 || ORIG_REF_NAME==design_2_xlslice_2_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_util_vector_logic_0_0/design_2_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_util_vector_logic_0_0 || ORIG_REF_NAME==design_2_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_util_vector_logic_1_0/design_2_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_util_vector_logic_1_0 || ORIG_REF_NAME==design_2_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_IDreg_0_0/design_2_IDreg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_IDreg_0_0 || ORIG_REF_NAME==design_2_IDreg_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_StatusReg_0_0/design_2_StatusReg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_StatusReg_0_0 || ORIG_REF_NAME==design_2_StatusReg_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlslice_2_1/design_2_xlslice_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlslice_2_1 || ORIG_REF_NAME==design_2_xlslice_2_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlslice_3_1/design_2_xlslice_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlslice_3_1 || ORIG_REF_NAME==design_2_xlslice_3_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlslice_4_0/design_2_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlslice_4_0 || ORIG_REF_NAME==design_2_xlslice_4_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_dist_mem_gen_0_0/design_2_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_dist_mem_gen_0_0 || ORIG_REF_NAME==design_2_dist_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_dist_mem_gen_1_0/design_2_dist_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_dist_mem_gen_1_0 || ORIG_REF_NAME==design_2_dist_mem_gen_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Val2Gen_0_0/design_2_Val2Gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_Val2Gen_0_0 || ORIG_REF_NAME==design_2_Val2Gen_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ALU_0_0/design_2_ALU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ALU_0_0 || ORIG_REF_NAME==design_2_ALU_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_util_vector_logic_0_1/design_2_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_util_vector_logic_0_1 || ORIG_REF_NAME==design_2_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlslice_0_1/design_2_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlslice_0_1 || ORIG_REF_NAME==design_2_xlslice_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ExeReg_0_0/design_2_ExeReg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ExeReg_0_0 || ORIG_REF_NAME==design_2_ExeReg_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Mux_1/design_2_Mux_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_Mux_1 || ORIG_REF_NAME==design_2_Mux_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_MEM_Stage_Reg_0_0/design_2_MEM_Stage_Reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_MEM_Stage_Reg_0_0 || ORIG_REF_NAME==design_2_MEM_Stage_Reg_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_HazardUnitDetector_0_0/design_2_HazardUnitDetector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_HazardUnitDetector_0_0 || ORIG_REF_NAME==design_2_HazardUnitDetector_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_util_vector_logic_0_2/design_2_util_vector_logic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_util_vector_logic_0_2 || ORIG_REF_NAME==design_2_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_util_vector_logic_0_3/design_2_util_vector_logic_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_util_vector_logic_0_3 || ORIG_REF_NAME==design_2_util_vector_logic_0_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_RedAdder_0_0/design_2_RedAdder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_RedAdder_0_0 || ORIG_REF_NAME==design_2_RedAdder_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlslice_0_2/design_2_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlslice_0_2 || ORIG_REF_NAME==design_2_xlslice_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ForwardingUnit_0_0/design_2_ForwardingUnit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ForwardingUnit_0_0 || ORIG_REF_NAME==design_2_ForwardingUnit_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Exe_Mux_0_0/design_2_Exe_Mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_Exe_Mux_0_0 || ORIG_REF_NAME==design_2_Exe_Mux_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Exe_Mux_0_1/design_2_Exe_Mux_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_Exe_Mux_0_1 || ORIG_REF_NAME==design_2_Exe_Mux_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_vio_0_0/design_2_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_vio_0_0 || ORIG_REF_NAME==design_2_vio_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_0_0/design_2_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_0 || ORIG_REF_NAME==design_2_xlconstant_0_0} -quiet] -quiet

# XDC: bd/design_2/design_2_ooc.xdc
